"""empty message

Revision ID: 1baf4b082575
Revises: 
Create Date: 2022-05-09 15:57:01.879042

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry


# revision identifiers, used by Alembic.
revision = '1baf4b082575'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(length=200), nullable=False),
                    sa.Column('location', Geometry(geometry_type='POINT',
                                                   from_text='ST_GeomFromEWKT', name='geometry', dimension=2, spatial_index=True, srid=4326), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_posts_location', 'posts', [
                    'location'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_posts_location', table_name='posts',
                  postgresql_using='gist', postgresql_ops={})
    op.drop_table('posts')
    # ### end Alembic commands ###
